sudo: required
dist: trusty


language: node_js
node_js:
  - "8"

before_install:
  - npm install karma-cli -g
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
  
script:
  - karma start
 
branches:
  only:
    - master
  
cache:
  directories:
  - node_modules

notifications:
  email: true