language: node_js
node_js:
  - "stable"

before_install:
  - npm install karma-cli -g

script:
  - karma start
 
branches:
  only:
    - master
  
cache:
  directories:
  - node_modules

notifications:
  email: true